Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 3306, host: 3306

    config.vm.boot_timeout = 300
    config.vm.synced_folder "./", "/var/www/html"
    config.vm.provision "file", source: "./resources/vagrant/php-8.3.2/apache/000-default.conf", destination: "/home/vagrant/000-default.conf"
    config.vm.provision "shell", path: "./resources/vagrant/php-8.3.2/scripts/provision.sh"
    config.ssh.insert_key = false
    config.ssh.extra_args = ["-t", "cd /var/www/html; bash --login"]

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
        vb.gui = false
        vb.name = "Lamp Development PHP-8.3.2"
        vb.memory = 2048
        vb.cpus = 2
   end
end
